'use client'
import { useEffect, useMemo, useState } from 'react'
import { Check, ChevronRight, Clock3, ShieldCheck, Wrench, X } from 'lucide-react'

type Job={id:string;name:string;type:string;laborHours:number;laborRate:number;partsPrice:number;decision:string;severity:string}
type Estimate={state:'open'|'responded'|'expired'|'invalid';expiresAt?:number;shop?:{name:string;phone:string;address:string};customer?:{name:string};vehicle?:{year:number;make:string;model:string;plate:string;mileage:number};order?:{id:string;taxRate:number;fees:number;discount:number;jobs:Job[]}}
const money=(value:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(value||0)

export default function EstimateApproval({token}:{token:string}){
 const [estimate,setEstimate]=useState<Estimate|null>(null),[choices,setChoices]=useState<Record<string,'Approved'|'Declined'>>({}),[name,setName]=useState(''),[consent,setConsent]=useState(false),[sending,setSending]=useState(false),[error,setError]=useState('')
 useEffect(()=>{fetch(`/api/approvals/${token}`,{cache:'no-store'}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error||'Could not open estimate.');setEstimate(body);if(body.customer?.name)setName(body.customer.name);const initial:Record<string,'Approved'|'Declined'>={};body.order?.jobs?.forEach((job:Job)=>{if(job.decision==='Approved'||job.decision==='Declined')initial[job.id]=job.decision});setChoices(initial)}).catch(e=>setError(e.message))},[token])
 const total=useMemo(()=>{if(!estimate?.order)return 0;const subtotal=estimate.order.jobs.filter(j=>choices[j.id]==='Approved').reduce((sum,j)=>sum+j.laborHours*j.laborRate+j.partsPrice,0);return (subtotal+estimate.order.fees-estimate.order.discount)*(1+estimate.order.taxRate/100)},[estimate,choices])
 const pending=estimate?.order?.jobs.filter(job=>job.decision==='Pending')||[],complete=pending.length>0&&pending.every(job=>choices[job.id])
 const submit=async()=>{if(!complete||!consent)return;setSending(true);setError('');try{const decisions=pending.map(job=>({jobId:job.id,decision:choices[job.id]}));const response=await fetch(`/api/approvals/${token}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({customerName:name,consent,decisions})});const body=await response.json();if(!response.ok)throw new Error(body.error||'Could not submit response.');setEstimate(current=>current?{...current,state:'responded'}:current)}catch(e){setError(e instanceof Error?e.message:'Could not submit response.')}finally{setSending(false)}}
 if(error&&!estimate)return <main className="estimate-public"><section className="estimate-message"><X/><h1>We couldn’t open this estimate</h1><p>{error}</p></section></main>
 if(!estimate)return <main className="estimate-public"><section className="estimate-message"><div className="estimate-spinner"/><h1>Opening your estimate…</h1></section></main>
 if(estimate.state==='invalid'||estimate.state==='expired')return <main className="estimate-public"><section className="estimate-message"><Clock3/><h1>{estimate.state==='expired'?'This link has expired':'This link is not valid'}</h1><p>Contact the repair shop and ask for a new secure estimate link.</p></section></main>
 if(estimate.state==='responded')return <main className="estimate-public"><section className="estimate-message success"><Check/><h1>Response received</h1><p>Thank you. {estimate.shop?.name} can now continue with the work you authorized.</p></section></main>
 return <main className="estimate-public"><header className="estimate-header"><div className="estimate-logo">G</div><div><b>{estimate.shop?.name}</b><span>{estimate.shop?.phone} {estimate.shop?.address&&`· ${estimate.shop.address}`}</span></div><ShieldCheck/></header><div className="estimate-wrap"><section className="estimate-hero"><small>SECURE ESTIMATE REVIEW</small><h1>Hi {estimate.customer?.name}, review your recommended services.</h1><p>{estimate.vehicle?.year} {estimate.vehicle?.make} {estimate.vehicle?.model} · {estimate.vehicle?.plate||'No plate'} · Repair order {estimate.order?.id}</p></section><div className="estimate-layout"><section><h2>Service recommendations</h2>{estimate.order?.jobs.map(job=>{const price=job.laborHours*job.laborRate+job.partsPrice,fixed=job.decision!=='Pending';return <article className="estimate-job" key={job.id}><div className="estimate-job-main"><div className="estimate-tool"><Wrench/></div><div><span className={`estimate-severity ${job.severity?.toLowerCase().replaceAll(' ','-')}`}>{job.severity}</span><h3>{job.name}</h3><p>{job.laborHours} labor hour{job.laborHours===1?'':'s'} · {money(job.partsPrice)} parts</p></div><b>{money(price)}</b></div><div className="estimate-decisions"><button disabled={fixed} className={choices[job.id]==='Approved'?'approve selected':'approve'} onClick={()=>setChoices(c=>({...c,[job.id]:'Approved'}))}><Check/> Approve</button><button disabled={fixed} className={choices[job.id]==='Declined'?'decline selected':'decline'} onClick={()=>setChoices(c=>({...c,[job.id]:'Declined'}))}><X/> Decline</button></div></article>})}</section><aside className="estimate-summary"><small>YOUR AUTHORIZED TOTAL</small><strong>{money(total)}</strong><p>Includes shop fees, discounts and {estimate.order?.taxRate||0}% tax where applicable.</p><label><span>Your name</span><input value={name} onChange={e=>setName(e.target.value)} /></label><label className="estimate-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>I authorize the approved services and understand declined work will not be performed.</span></label>{error&&<p className="estimate-error">{error}</p>}<button className="estimate-submit" disabled={!complete||!consent||name.trim().length<2||sending} onClick={submit}>{sending?'Submitting…':'Submit response'} <ChevronRight/></button><div className="estimate-secure"><ShieldCheck/> Secure, expiring link · no payment information requested</div></aside></div></div></main>
}
